### ISSUE TITLE
You should try to calculate the gradient of the cost function analytically

### ISSUE THREAD

**Issue by jgomezdans** [Adizlois/Biophysical-parameter-estimation#2]
You don't have the gradient for the RT model, but you can easily approximate it by finite differences.

**Comment by Adizlois** [comment]
Sure! But that is also the method used by many optimization packages. More specifically, in this case scipy.optimize.minimize docs states that: " the gradient will be estimated using ‘2-point’ finite difference estimation".

**Comment by jgomezdans** [comment]
yes, but in general, you shouldn't try to rely on this, but rather have an analytical gradient, as finite differences are approximations and slow once the number of parameters goes up. I want to see that, even though you won't have all the relevant information for PROSAIL, so you'll need to figure that one out.

**Comment by Adizlois** [comment]
In the last update I included another method using the derivative. I hope it fulfills your expectations. ;)

**Comment by jgomezdans** [comment]
Refer to the opened issue in the commit and close it if necessary (but give description of the change)
